import test from 'node:test';import assert from 'node:assert/strict';import ts from 'typescript';import fs from 'node:fs';
async function load(path){const source=ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText;return import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));}
test('Area, RT and Area-logo filters keep national logos and distinguish areas',async()=>{const {matchesLogo,originals,logoScope,groupedLogos}=await load('lib/catalog.ts');assert.ok(matchesLogo(originals[0],'1','400','All'));assert.equal(matchesLogo(originals[1],'1','All','Area'),false);assert.ok(matchesLogo(originals[1],'18','All','Area'));assert.ok(matchesLogo({area:18,rt:400,category:'Table'},'18','400','Table'));assert.equal(matchesLogo({area:18,rt:400,category:'Table'},'18','1','Table'),false);assert.equal(logoScope(originals[0]),'Official');assert.equal(logoScope(originals[1]),'Area · Area 18');assert.equal(logoScope({category:'Table',area:7,rt:12}),'Table · Area 7 · RT 12');assert.equal(logoScope({category:'Table',area:7,rt:12,tableKind:'chairman'}),'Table · Chairman theme · Area 7 · RT 12');assert.deepEqual(groupedLogos(originals).map(g=>g.category),['Official','Area']);const chairman={area:18,rt:42,category:'Table',tableKind:'chairman'};assert.equal(matchesLogo(chairman,'18','All','Table'),false);assert.ok(matchesLogo(chairman,'18','42','Table'));});
test('Upload metadata generates RT/Area labels and validates boundaries',async()=>{const {logoFields}=await load('lib/validation.ts');const f=new FormData();f.set('category','Table');f.set('area','18');f.set('rt','400');assert.deepEqual(logoFields(f,false),{name:'RT 400',category:'Table',area:18,rt:400,tableKind:'standard'});f.set('table_kind','chairman');f.set('name','Chairman 2026–27');assert.deepEqual(logoFields(f,false),{name:'Chairman 2026–27',category:'Table',area:18,rt:400,tableKind:'chairman'});f.set('rt','401');assert.throws(()=>logoFields(f,false),/RT/);f.set('category','Area');f.set('table_kind','standard');f.set('rt','400');f.delete('name');assert.throws(()=>logoFields(f,false),/name/);f.set('name','Area 18 Gala');assert.equal(logoFields(f,false).name,'Area 18 Gala');f.set('area','0');assert.throws(()=>logoFields(f,false),/Area/);});
test('Logo uploads allow files up to 10 MB',async()=>{const {MAX_LOGO_BYTES}=await load('lib/validation.ts');assert.equal(MAX_LOGO_BYTES,10_000_000);});
test('Activity tag labels trim whitespace and enforce length',async()=>{const {activityTagLabel}=await load('lib/tags.ts');assert.equal(activityTagLabel('  Blood donation  '),'Blood donation');assert.throws(()=>activityTagLabel(''),/tag/);assert.throws(()=>activityTagLabel('x'.repeat(81)),/tag/);});
test('Flyer export names keep a stable JPEG suffix',async()=>{const {flyerExportName}=await load('lib/export-flyer.ts');assert.equal(flyerExportName('blood-drive.png'),'blood-drive-area18.jpg');assert.equal(flyerExportName('flyer'),'flyer-area18.jpg');});
test('Share flyer uses files-only payloads for mobile share sheets',async()=>{const {buildShareFile}=await load('lib/export-flyer.ts');const file=buildShareFile(new Blob(['x'],{type:'image/jpeg'}),'demo-area18.jpg');assert.equal(file.type,'image/jpeg');assert.equal(file.name,'demo-area18.jpg');});
test('Logo asset URLs include a stable version token',async()=>{const {withLogoVersion}=await load('lib/logo-url.ts');assert.equal(withLogoVersion('/api/logos/abc','2026-01-01'),'/api/logos/abc?v=2026-01-01');assert.equal(withLogoVersion('/logos/rti.png?v=1','2'),'/logos/rti.png?v=1&v=2');});
