'use client';
import { Plus,Trash2 } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { Checkbox } from '@/components/ui/checkbox';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { activityTags,fonts,type Design,type TextLayer } from '@/lib/composite';
function Choice({label,value,items,onChange}:{label:string;value:string;items:string[][];onChange:(v:string)=>void}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="picker" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select>;}
function Range({label,value,min,max,onChange}:{label:string;value:number;min:number;max:number;onChange:(v:number)=>void}){return <label className="range-field"><span>{label}<small>{value}%</small></span><Slider aria-label={label} value={[value]} min={min} max={max} step={1} onValueChange={v=>onChange(v[0])}/></label>;}
export default function DesignControls({design,setDesign}:{design:Design;setDesign:(d:Design)=>void}){function patch(id:string,v:Partial<TextLayer>){setDesign({...design,textLayers:design.textLayers.map(t=>t.id===id?{...t,...v}:t)});}return <><section className="panel"><h2><span className="step">3</span> Activity tags</h2><p className="hint">Selected tags appear below the logos.</p><div className="tag-choices">{activityTags.map(tag=><label key={tag} className={'tag-choice '+(design.tags.includes(tag)?'active':'')}><Checkbox checked={design.tags.includes(tag)} onCheckedChange={checked=>setDesign({...design,tags:checked?[...design.tags,tag]:design.tags.filter(t=>t!==tag)})}/>{tag}</label>)}</div></section><section className="panel"><div className="section-line"><h2><span className="step">4</span> Add text</h2><span className="count">{design.textLayers.length}/6</span></div><p className="hint">Text is added over your flyer. Use a design with space for it.</p>{design.textLayers.map((t,i)=><div key={t.id} className="text-layer"><div className="section-line"><strong>Text {i+1}</strong><button className="delete" aria-label={'Remove text '+(i+1)} onClick={()=>setDesign({...design,textLayers:design.textLayers.filter(x=>x.id!==t.id)})}><Trash2 size={16}/></button></div><label className="field">Your text<textarea maxLength={500} rows={3} value={t.text} onChange={e=>patch(t.id,{text:e.target.value})} placeholder="Event title, date, venue…"/></label><label className="field">Font<Choice label={'Font for text '+(i+1)} value={t.font} items={fonts} onChange={font=>patch(t.id,{font})}/></label><p className="font-sample" style={{fontFamily:t.font}}>{t.text.split('\n')[0]||'Celebrate together'}</p><div className="text-tools"><label className="colour-field">Colour<input type="color" value={t.color} onChange={e=>patch(t.id,{color:e.target.value})}/></label><Choice label={'Alignment for text '+(i+1)} value={t.align} items={['left','center','right'].map(v=>[v,v[0].toUpperCase()+v.slice(1)])} onChange={align=>patch(t.id,{align:align as TextLayer['align']})}/></div><Range label="Text size" min={1} max={15} value={t.size} onChange={size=>patch(t.id,{size})}/><Range label="Horizontal position" min={5} max={95} value={t.x} onChange={x=>patch(t.id,{x})}/><Range label="Vertical position" min={0} max={100} value={t.y} onChange={y=>patch(t.id,{y})}/></div>)}<button className="secondary" disabled={design.textLayers.length>=6} onClick={()=>setDesign({...design,textLayers:[...design.textLayers,{id:crypto.randomUUID(),text:'',font:'Modern',color:'#ffffff',size:5,x:50,y:35,align:'center'}]})}><Plus size={16}/> Add text block</button></section></>;}
