import type { Logo } from './catalog';
export type Placement='header'|'footer'|'reserved-top'|'reserved-bottom';
export const activityTags=['LAPD Experience','Go Go Green','Community Service Activity','Business Meet','Socials','Fellowship','JAFFA','AEX','NEX','MTM'];
export const fonts=[['Modern','Modern Bold'],['Script','Celebration Script'],['Geometric','Geometric'],['Classic','Classic Serif'],['Condensed','Bold Condensed']];
export type TextLayer={id:string;text:string;font:string;color:string;size:number;x:number;y:number;align:'left'|'center'|'right'};
export type Design={background:string;tags:string[];textLayers:TextLayer[]};
export function loadImage(src:string):Promise<HTMLImageElement>{return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('An image could not be loaded. Refresh the logo collection and try again.'));image.src=src;});}
export function layout(width:number,height:number,count:number,placement:Placement,extra=0){const columns=Math.min(4,count),rows=Math.ceil(count/4),logoBand=Math.round(width*.26*rows),band=logoBand+extra,extend=placement==='header'||placement==='footer';if(!extend&&band>height*.45)throw new Error('This content needs more space. Use an added header or footer.');const outputHeight=height+(extend?band:0);if(width*outputHeight>24000000||width>8000||outputHeight>10000)throw new Error('This flyer is too large for export. Use an image up to 24 megapixels with sides below 8,000 × 10,000 pixels.');return {columns,rows,band,logoBand,outputHeight,flyerY:placement==='header'?band:0,bandY:placement==='footer'?height:placement==='reserved-bottom'?height-band:0};}
export function wrap(ctx:CanvasRenderingContext2D,text:string,width:number){const lines:string[]=[];for(const paragraph of text.split('\n')){let line='';for(const char of paragraph){if(line&&ctx.measureText(line+char).width>width){lines.push(line.trimEnd());line=char.trimStart();}else line+=char;}lines.push(line);}return lines;}
export async function compose(canvas:HTMLCanvasElement,flyer:HTMLImageElement,logos:Logo[],placement:Placement,design:Design={background:'#000000',tags:[],textLayers:[]}){if(!logos.length)throw new Error('Choose at least one logo.');const loaded=await Promise.all(logos.map(l=>loadImage(l.url)));if(typeof document!=='undefined'){await Promise.all([...new Set(['Modern',...design.textLayers.map(t=>t.font)])].map(f=>document.fonts.load(`24px "${f}"`)));}
 const w=flyer.naturalWidth,h=flyer.naturalHeight,ctx=canvas.getContext('2d');if(!ctx)throw new Error('Image export is unavailable in this browser.');const pad=w*.025,tagSize=w*.021,tagH=w*.048,tagGap=w*.012;ctx.font=`${tagSize}px "Modern", sans-serif`;const tagRows:{text:string;width:number}[][]=[];let row:{text:string;width:number}[]=[],rowWidth=0;for(const text of design.tags){const width=ctx.measureText(text).width+pad;if(row.length&&rowWidth+width>w-2*pad){tagRows.push(row);row=[];rowWidth=0;}row.push({text,width});rowWidth+=width+tagGap;}if(row.length)tagRows.push(row);const extra=tagRows.length?Math.ceil(tagRows.length*(tagH+tagGap)+pad):0;const l=layout(w,h,logos.length,placement,extra);canvas.width=w;canvas.height=l.outputHeight;
 // JPEG has no alpha. Explicitly flatten transparent flyer pixels onto white.
 ctx.fillStyle='#ffffff';ctx.fillRect(0,0,w,l.outputHeight);ctx.drawImage(flyer,0,l.flyerY);ctx.fillStyle=design.background;ctx.fillRect(0,l.bandY,w,l.band);
 const rowH=l.logoBand/l.rows;loaded.forEach((image,i)=>{const row=Math.floor(i/4),inRow=Math.min(4,logos.length-row*4),cellW=w/inRow,padding=Math.max(12,w*.018);const [sx,sy,sw,sh]=logos[i].sourceRect??[0,0,image.naturalWidth,image.naturalHeight];const scale=Math.min((cellW-2*padding)/sw,(rowH-2*padding)/sh),dw=sw*scale,dh=sh*scale;ctx.drawImage(image,sx,sy,sw,sh,cellW*(i%4)+(cellW-dw)/2,l.bandY+row*rowH+(rowH-dh)/2,dw,dh);});
 const rgb=design.background.replace('#','');const luminance=parseInt(rgb.slice(0,2),16)*.299+parseInt(rgb.slice(2,4),16)*.587+parseInt(rgb.slice(4,6),16)*.114;const ink=luminance>150?'#15243c':'#ffffff';ctx.font=`${tagSize}px "Modern", sans-serif`;ctx.textBaseline='middle';ctx.textAlign='center';tagRows.forEach((items,index)=>{const total=items.reduce((a,t)=>a+t.width,0)+(items.length-1)*tagGap;let x=(w-total)/2;const y=l.bandY+l.logoBand+index*(tagH+tagGap);for(const t of items){ctx.fillStyle=luminance>150?'rgba(0,0,0,0.08)':'rgba(255,255,255,0.14)';ctx.beginPath();ctx.roundRect(x,y,t.width,tagH,tagH/2);ctx.fill();ctx.fillStyle=ink;ctx.fillText(t.text,x+t.width/2,y+tagH/2);x+=t.width+tagGap;}});
 // Keep added text inside the flyer artwork; never draw over original logo pixels.
 const top=placement==='reserved-top'?l.band:0,bottom=placement==='reserved-bottom'?h-l.band:h,usableH=bottom-top;
 for(const t of design.textLayers){if(!t.text.trim())continue;const size=w*t.size/100;ctx.font=`${size}px "${t.font}"`;const x=w*t.x/100,maxWidth=Math.max(w*.05, t.align==='left'?w-pad-x:t.align==='right'?x-pad:2*Math.min(x-pad,w-pad-x));const lines=wrap(ctx,t.text,Math.max(w*.05,maxWidth));const lineHeight=size*1.25;const textH=lines.length*lineHeight;if(textH>usableH-2*pad)throw new Error('Text is too tall for this flyer. Reduce its size or shorten it.');const y=l.flyerY+top+pad+(usableH-2*pad-textH)*t.y/100;ctx.save();ctx.beginPath();ctx.rect(pad,l.flyerY+top,w-2*pad,usableH);ctx.clip();ctx.fillStyle=t.color;ctx.textBaseline='top';ctx.textAlign=t.align;lines.forEach((line,i)=>ctx.fillText(line,x,y+i*lineHeight));ctx.restore();}return l;}
